import streamlit as st

st.set_page_config(
    page_title="Home"
)

st.write("""
# <span style="color:#D2D0A0">Ecolet</span>

We will be demostrating machine learning model to predict food waste.

## <span style="color:#9EBC8A">Background Description</span>
         
Under the Singapore Green Plan 2030, food waste has emerged as a critical environmental \
and social challenge. The F&B sector alone generates over one-third of the country’s \
total food waste annually, yet predictive measures remain underutilized. There is a \
growing push to forecast food waste patterns across different types of restaurants to \
inform policy, technology interventions, and consumer education campaigns. 

However, multiple factors complicate this effort. Many restaurants are reluctant \
to adopt digital food waste tracking systems due to fears of reputational harm, \
regulatory exposure, and consumer backlash. Cultural practices, such as overproduction \
in buffet-style dining or "face-saving" banquets, further normalize excess and limit \
the perceived urgency of reform. Additionally, incentive misalignment between industry \
and government continues to hinder systemic innovation and accountability. 

To address this issue, this project proposes the use of a Multiple Linear Regression (MLR) \
model to predict the amount of food waste generated by restaurants based on factors

## <span style="color:#73946B">User Persona</span>
1. **Rachel Jung – Hotel Buffet Operation Manager**

   Sector:  4-star hotel F&B operations, Singapore

   Job Desks / Responsibilities

   - Oversee daily buffet operations across multiple meal periods
   - Manage food preparation volumes to meet fluctuating guest traffic
   - Maintain high standards for food quality, presentation, and hygiene

   Pain Points

   - Inconsistent food waste tracking: Waste is recorded manually and lacks proper categorization
   - Daily fluctuations in guest turnout make it hard to prep accurate quantities
   - Lacks predictive tools to anticipate high/low demand periods
   - Manual logs delay insights — can’t adjust on the fly

2.  **Mr. Tan Boon Huat – Hawker Stall Owner**

    Sector: Single-Stall Hawker | Age: 62

    Job Desks / Responsibilities

    - Manage inventory and food prep daily
    - Keep ingredient costs low while maintaining food quality
    - Ensure compliance with food safety and hygiene rules

    Pain Points

    - Frequent overestimation leads to daily ingredient waste 
    - No/limited cold storage space = spoilage after closing hours

3.  **Nurul Aisyah – Fast Food Restaurant Manager**

    Sector: International Fast Food Chain | Age: 30

    Job Desks / Responsibilities

    - Meet monthly cost-efficiency targets
    - Monitor food prep and inventory levels
    - Prepare for ESG audits

    Pain Points

    - Over-prepping during rush hours causes end-of-day waste 
         
## <span style="color:#537D5D">Problem Statement</span>
"How might we predict the amount of food waste generated at events or restaurants \
based on operational, environmental, and economic factors such as quantity of food \
prepared, number of guests, event type, and pricing strategy—so as to minimize unnecessary waste?"
""", unsafe_allow_html=True)
