import streamlit as st

st.set_page_config(
    page_title="Home"
)

st.write("""
# <span style="color:#537D5D">ECOLET</span>

We will be demostrating machine learning model to predict food waste.

## <span style="color:#9EBC8A">Background Description</span>
         
Under the Singapore Green Plan 2030, food waste has emerged as a critical environmental \
and social challenge. The F&B sector alone generates over one-third of the country’s \
total food waste annually, yet predictive measures remain underutilized. There is a \
growing push to forecast food waste patterns across different types of restaurants to \
inform policy, technology interventions, and consumer education campaigns. 

To address this issue, this project proposes the use of a Multiple Linear Regression (MLR) \
model to predict the amount of food waste generated by restaurants based on factors
""", unsafe_allow_html=True)

st.write("""
## <span style="color:#9EBC8A">User Persona</span>
""", unsafe_allow_html=True)
st.image("./image/User_Persona.png")


st.write("""
## <span style="color:#9EBC8A">Problem Statement</span>
"How might we predict the amount of food waste generated at events or restaurants \
based on operational, environmental, and economic factors such as quantity of food \
prepared, number of guests, event type, and pricing strategy—so as to minimize unnecessary waste?"
""", unsafe_allow_html=True)
